name: CI
on: [ push, pull_request ]
jobs:
  checks:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: npm ci --ignore-scripts
      - run: npm run lint
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '16.x' ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - name: Setting up Node.js (v${{ matrix.node-version }}.x)
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --ignore-scripts
      - run: npm run test
      - run: npm install coveralls --save-dev
        if: ${{ matrix.node-version == '16.x' }}
      - run: cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
      - run: codecov -f ./coverage/clover.xml -t ${{ secrets.CODECOV_TOKEN }} --commit=$GITHUB_SHA --branch=${GITHUB_REF##*/}
        if: ${{ matrix.node-version == '16.x' }}
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: npm ci --ignore-scripts
      - run: npm run build:libs
